---
- name: DEPLOY AS3 DEC
  hosts: localhost
  connection: local
  gather_facts: no  

  vars:
    uri_method: POST

  vars_files:
    - ../creds/big_creds.yaml

  tasks:
    
  - name: Create AS3 declaration
    uri:
      url: https://20.39.162.40//mgmt/shared/appsvcs/declare/
      user: "{{bigip_user}}"
      password: "{{bigip_pass}}"
      method: "{{uri_method}}"
      body: "{{ lookup('file','AS3.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no

...